# Target clusters where this app should be deployed
# Set to "true" to deploy, "false" or omit to skip
target-test: "true"
target-dev: "true"
target-staging: "true"
target-infra: "false"
target-prod-us: "true"
target-prod-eu: "true"
target-prod-au: "true"
