# Target clusters where this app should be deployed
# Remove clusters from this list to skip deployment on those clusters
targetClusters:
  - test
  - dev
  - staging
  - prod-us
  - prod-eu
  - prod-au
