# Simple go http server values for: prod-us cluster

replicaCount: 3

environmentVariables:
  - name: Environment
    value: "prod-us"

ingress:
  hosts:
    - host: simple-go-http-server.prod-us.local
      paths:
        - path: /
          pathType: ImplementationSpecific
