# Simple go http server values for: staging cluster

replicaCount: 1

environmentVariables:
  - name: Environment
    value: "staging"

ingress:
  hosts:
    - host: simple-go-http-server.staging.local
      paths:
        - path: /
          pathType: ImplementationSpecific
