# Simple go http server values for: prod-eu cluster

replicaCount: 3

environmentVariables:
  - name: Environment
    value: "prod-eu"

ingress:
  hosts:
    - host: simple-go-http-server.prod-eu.local
      paths:
        - path: /
          pathType: ImplementationSpecific
